;;; ~/.doom.d/config.windows.el -*- lexical-binding: t; -*-

(require 'server)
(unless (server-running-p) (server-start))

(setq browse-url-browser-function 'browse-url-default-windows-browser)
(setq w32-get-true-file-attributes nil)
(let ((find "c:/tools/msys64/usr/bin/find.exe")
      (grep "c:/tools/msys64/usr/bin/grep.exe")
      (diff "c:/tools/msys64/usr/bin/diff.exe")
      (diff3 "c:/tools/msys64/usr/bin/diff3.exe")
      (cmp "c:/tools/msys64/usr/bin/cmp.exe"))
  (when (file-exists-p find)
    (setq find-program find))
  (when (file-exists-p grep)
    (setq grep-program grep))
  (when (file-exists-p diff)
    (setq ediff-diff-program diff))
  (when (file-exists-p diff3)
    (setq ediff-diff3-program diff3))
  (when (file-exists-p cmp)
    (setq ediff-cmp-program cmp)))

(setenv "SSH_ASKPASS" "git-gui--askpass")
(magit-auto-revert-mode -1)
